runtime: python39
service: story-teller
entrypoint: uvicorn --port $PORT main:app

env_variables:
  OPENAI_API_KEY:

basic_scaling:
  max_instances: 11
  idle_timeout: 10m

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
  - url: /static
    static_dir: static

    # This handler routes all requests not caught above to your main app. It is
    # required when static routes are defined, but can be omitted (along with
    # the entire handlers section) when there are no static files defined.
  - url: /.*
    script: auto
