runtime: python
service: story-teller
#entrypoint: uvicorn --port $PORT main:app
entrypoint: gunicorn -b :$PORT -w 4 -k uvicorn.workers.UvicornWorker --forwarded-allow-ips="*" main:app

env_variables:
  OPENAI_API_KEY:

# basic_scaling:
#   max_instances: 11
#   idle_timeout: 10m

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
  - url: /static
    static_dir: static

    # This handler routes all requests not caught above to your main app. It is
    # required when static routes are defined, but can be omitted (along with
    # the entire handlers section) when there are no static files defined.
  - url: /.*
    script: auto

env: flex
instance_class: F1
runtime_config:
  operating_system: ubuntu22
  python_version: 3

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
